# Natron
natron:
  branch: 2.4
  release:
    version: 2.4.0
    date: '2021-04-20'
    url:
      tag: 'https://github.com/NatronGitHub/Natron/releases/tag/v'
      download: 'https://github.com/NatronGitHub/Natron/releases/download/v'
    linux:
      installer: '-Linux-x86_64.tgz'
      portable: '-Linux-x86_64-no-installer.tar.xz'
      flatpak: 'https://flathub.org/apps/details/fr.natron.Natron'
    windows: '-Windows-x86_64.zip'
    macos:
      v11: '-macOS11-x86_64.dmg'
      v1015: '-macOS1015-x86_64.dmg'
      v109: '-OSX109-x86_64.dmg'
      v106: '-OSX-Universal.dmg'

# General
title: 'Natron'
description: 'Open Source Compositing Software For VFX and Motion Graphics'

# Home
home:
  hero:
    image: 'img/natron-baymax-screenshot.png'
    title: 'Visual Effects Without Limits.'
    description: 'Node-based compositing, backed by the freedom of open-source.'
    button:
      title: 'Download Natron'
      url: '#download'
  features:
    title: 'The tools you ºd expect to be here'
    description: 'The standard 2D compositing toolkit you already know and love.'
    items:
      openfx:
        image: 'img/index-feature-cards/openfx.svg'
        title: 'OpenFX Plugin Support'
        description: 'Natron supports industry-standard OFX plug-ins.'
      tracking:
        image: 'img/index-feature-cards/tracking.svg'
        title: '2D Tracking'
        description: 'Natron includes a fast, pixel-perfect 2D tracker.'
      roto:
        image: 'img/index-feature-cards/roto.svg'
        title: 'Roto'
        description: 'Multi-layered rotoscoping with per-vertex feathering.'
      keyer:
        image: 'img/index-feature-cards/keyer.svg'
        title: 'Keying'
        description: 'Natron offers various keying and matte refinement tools.'
      dopesheet:
        image: 'img/index-feature-cards/dopesheet.svg'
        title: 'Curve & Dope-sheet Editors'
        description: "If you've used a curve editor before you know how to use this one too."
      rendering:
        image: 'img/index-feature-cards/gpu.svg'
        title: 'GPU & Network Rendering'
        description: 'Natron is GPU accelerated and can be integrated with render farm managers.'

# Guide
guide:
  intro: 'guide/intro.html'
  getting_started: 'guide/getstarted.html'
  compositing: 'guide/compositing.html'
  tutorials: 'guide/tutorials.html'
  reference: '_group.html'
  developer: 'devel/index.html'

# External
# twitter: https://twitter.com/natronvfx (unmaintained)
discord: 'https://discord.gg/cpMj5p3Fv5'
forum: 'https://discuss.pixls.us/c/software/natron'
github: 'https://github.com/NatronGitHub/Natron'
facebook: 'https://facebook.com/groups/NatronNation'
docs: 'https://natron.readthedocs.io'
demos: 'https://sourceforge.net/projects/natron/files/Examples'

# Build settings
sass:
  style: compressed
markdown: kramdown
kramdown:
  auto_ids: "true"
  input: GFM
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
collections_dir: _collections
collections:
  features:
    output: true
    permalink: /features/:path/
plugins:
  - jekyll-feed
  - jekyll-redirect-from
