# Natron
#
# Update 'branch', 'version' and 'date' on new release
# also make a new post in '_posts' named 'YYYY-MM-DD-Natron-X-Y-Z.md' (just copy the content of the GitHub release notes)
# and update 'LATEST_VERSION.txt'
#
natron:
  branch: 2.4
  release:
    version: 2.4.0
    date: '2021-04-20'
    url:
      base: 'https://github.com/NatronGitHub/Natron/releases/'
      tag: 'tag/v'
      download: 'download/v'

# General
title: 'Natron'
description: 'Open Source Compositing Software For VFX and Motion Graphics'
#docs: 'https://natron.readthedocs.io'
#demos: 'https://sourceforge.net/projects/natron/files/Examples'

# Downloads
downloads:
  title: 'Download Natron'
  description: 'Latest version:'
  items:
    windows:
      title: 'Windows'
      description: 'Supports Windows 8.1/10/11 x64.'
      icon: 'bxl-windows'
      versions:
        installer:
          title: 'Installer & Portable'
          url: ''
          suffix: '-Windows-x86_64.zip'
    linux:
      title: 'GNU/Linux'
      description: 'Supports any x86_64 distribution with X11, glibc 2.17+ and libgcc 4.8+.'
      icon: 'bxl-tux'
      versions:
        installer:
          title: 'Installer'
          url: ''
          suffix: '-Linux-x86_64.tgz'
        portable:
          title: 'Portable'
          url: ''
          suffix: '-Linux-x86_64-no-installer.tar.xz'
        flatpak:
          title: 'Flatpak'
          url: 'https://flathub.org/apps/details/fr.natron.Natron'
          suffix: ''
    macos:
      title: 'macOS'
      description: 'Supports from Snow Leopard up to the latest version of macOS running on Intel hardware.'
      icon: 'bxl-apple'
      versions:
        v11:
          title: 'Big Sur and later'
          url: ''
          suffix: '-macOS11-x86_64.dmg'
        v1015:
          title: 'Catalina'
          url: ''
          suffix: '-macOS1015-x86_64.dmg'
        v109:
          title: 'Mavericks, Yosemite, El Capitan, (High) Sierra, Mojave'
          url: ''
          suffix: '-OSX109-x86_64.dmg'
        v106:
          title: 'Snow Leopard, (Mountain) Lion'
          url: ''
          suffix: '-OSX-Universal.dmg'

# Addons
addons:
  title: 'Add-ons'
  description: 'Additional plug-ins and scripts for Natron.'
  icon: 'bx-package'
  url: 'https://github.com/NatronGitHub/'
  items:
    natron_plugins:
      title: 'Natron Community plug-ins'
      url: 'natron-plugins'
    natron_scripts:
      title: 'Natron Community scripts'
      url: 'natron-python-scripting'
    openfx_braw:
      title: 'Blackmagic RAW plug-in'
      url: 'openfx-braw'
    openfx_community:
      title: 'OpenFX Community plug-ins'
      url: 'openfx-community'

# Sources
sourcecode:
  title: 'Sources'
  description: 'Source code for Natron and plug-ins.'
  icon: 'bx-package'
  url: 'https://github.com/NatronGitHub/'
  items:
    natron:
      title: 'Natron'
      url: 'Natron'
    openfx_io:
      title: 'OpenFX IO'
      url: 'openfx-io'
    openfx_misc:
      title: 'OpenFX Misc'
      url: 'openfx-misc'
    openfx_arena:
      title: 'OpenFX Arena'
      url: 'openfx-arena'
    openfx_gmic:
      title: 'OpenFX GMIC'
      url: 'openfx-gmic'

# Examples
examples:
  title: 'Examples'
  description: 'Natron example projects.'
  icon: 'bx-image'
  url: 'https://sourceforge.net/projects/natron/files/Examples/'
  items:
    spaceship:
      title: 'Spaceship'
      url: 'Natron_2.3.12_Spaceship.zip/download'
    baymax:
      title: 'BayMax'
      url: 'Natron_2.3.12_BayMax.zip/download'
    gnuvolador:
      title: 'GNUVolador'
      url: 'Natron_2.3.12_GNUVolador.zip/download'

# Home
home:
  hero:
    image: 'img/natron-baymax-screenshot.png'
    title: 'Visual Effects Without Limits.'
    description: 'Node-based compositing, backed by the freedom of open-source.'
    button:
      title: 'Download Natron'
      url: '#download'
      icon: 'bxs-download'
  features:
    title: 'The tools youʼd expect to be here'
    description: 'The standard 2D compositing toolkit you already know and love.'
    items:
      openfx:
        image: 'img/index-feature-cards/openfx.svg'
        title: 'OpenFX Plugin Support'
        description: 'Natron supports industry-standard OFX plug-ins.'
      tracking:
        image: 'img/index-feature-cards/tracking.svg'
        title: '2D Tracking'
        description: 'Natron includes a fast, pixel-perfect 2D tracker.'
      roto:
        image: 'img/index-feature-cards/roto.svg'
        title: 'Roto'
        description: 'Multi-layered rotoscoping with per-vertex feathering.'
      keyer:
        image: 'img/index-feature-cards/keyer.svg'
        title: 'Keying'
        description: 'Natron offers various keying and matte refinement tools.'
      dopesheet:
        image: 'img/index-feature-cards/dopesheet.svg'
        title: 'Curve & Dope-sheet Editors'
        description: "If you've used a curve editor before you know how to use this one too."
      rendering:
        image: 'img/index-feature-cards/gpu.svg'
        title: 'GPU & Network Rendering'
        description: 'Natron is GPU accelerated and can be integrated with render farm managers.'
  aboutnodes:
    image:
      url: 'img/natron-screenshot.png'
      alt: "A flatscreen monitor displaying Natron's interface"
    title: 'Work smarter with nodes'
    description:
      items:
        paragraph1:
          content: 'No more frustrating hunts through nested precomps! Fusion and Nuke users will be right at home in Natron’s node graph. Group, merge, and tinker to achieve just about any effect. Create pixel perfect mattes, cleanplates, and set extensions, all with node trees.'
        paragraph2:
          content: 'Build, group, and save your own nodes to create custom tools and presets. Or install from our large selection of community-made <a href="https://github.com/NatronGitHub/natron-plugins" target="_blank" class="intext-link intext-link-glow">“pyplug”</a> nodes.'

# Explore (header/footer menu)
explore:
  title: 'Explore'
  items:
    home:
      title: 'Home'
      url:
        link: ''
        external: false
      header: false
      footer: true
    downloads:
      title: 'Downloads'
      url:
        link: '#download'
        external: false
      header: true
      footer: true
    news:
      title: 'News'
      url:
        link: '#news'
        external: false
      header: true
      footer: true
    features:
      title: 'Features'
      url:
        link: '#features'
        external: false
      header: true
      footer: true
    community:
      title: 'Community'
      url:
        link: '#community'
        external: false
      header: true
      footer: true
    documentation:
      title: 'Documentation'
      url:
        link: 'https://natron.readthedocs.io'
        external: true
      header: false
      footer: true

# Learn (footer)
learn:
  title: 'Learn'
  url: 'https://natron.readthedocs.io'
  items:
    intro:
      title: 'What is compositing?'
      url: 'guide/intro.html'
    getting_started:
      title: 'Getting Started'
      url: 'guide/getstarted.html'
    compositing:
      title: 'Compositing'
      url: 'guide/compositing.html'
    tutorials:
      title: 'Tutorials'
      url: 'guide/tutorials.html'
    reference:
      title: 'Reference Guide'
      url: '_group.html'
    developer:
      title: 'Developers Guide'
      url: 'devel/index.html'

# Community (home/footer)
#
# https://twitter.com/natronvfx (unmaintained)
#
community:
  title:
    home: 'Join the community!'
    footer: 'Community'
  description:
    home: ''
    footer: 'Follow us on social media for the latest on Natron!'
  items:
    github:
      icon: 'bxl-github'
      title: 'Contribute on GitHub'
      description: 'Source code, bug reports, and build guides for developers!'
      url: 'https://github.com/NatronGitHub/Natron'
    pixls:
      icon: 'bxl-discourse'
      title: 'Discuss on the forum'
      description: 'The official place for questions and discussion about Natron!'
      url: 'https://discuss.pixls.us/c/software/natron'
    facebook:
      icon: 'bxl-facebook-circle'
      title: 'Find us on Facebook'
      description: 'Join the Natron Nation group on Facebook!'
      url: 'https://facebook.com/groups/NatronNation'
    discord:
      icon: 'bxl-discord'
      title: 'Join us on Discord'
      description: 'If you prefer text chat, check out the Discord server!'
      url: 'https://discord.gg/cpMj5p3Fv5'

# Build settings
sass:
  style: compressed
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
#collections_dir: _collections
#collections:
#  features:
#    output: true
#    permalink: /features/:path/
plugins:
  - jekyll-feed
  - jekyll-redirect-from
