# General
title: "Natron"
description: Open Source Compositing Software For VFX and Motion Graphics

# External
# twitter: https://twitter.com/natronvfx (unmaintained)
discord: https://discord.gg/cpMj5p3Fv5
forum: https://discuss.pixls.us/c/software/natron
github: https://github.com/NatronGitHub/Natron
facebook: https://facebook.com/groups/NatronNation
docs: https://natron.readthedocs.io
demos: https://sourceforge.net/projects/natron/files/Examples

# Guide
guide:
  intro: 'https://natron.readthedocs.io/en/rb-__BRANCH__/guide/intro.html'
  getting_started: 'https://natron.readthedocs.io/en/rb-__BRANCH__/guide/getstarted.html'
  compositing: 'https://natron.readthedocs.io/en/rb-__BRANCH__/guide/compositing.html'
  tutorials: https://natron.readthedocs.io/en/rb-__BRANCH__/guide/tutorials.html
  reference: 'https://natron.readthedocs.io/en/rb-__BRANCH__/_group.html'
  developer: 'https://natron.readthedocs.io/en/rb-__BRANCH__/devel/index.html'

# Natron
natron:
  branch: 2.4

# Build settings
sass:
  style: compressed
markdown: kramdown
kramdown:
  auto_ids: "true"
  input: GFM
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
collections_dir: _collections
collections:
  features:
    output: true
    permalink: /features/:path/
plugins:
  - jekyll-feed
  - jekyll-redirect-from
