# Natron
natron:
  branch: 2.4
  release:
    version: 2.4.0
    date: '2021-04-20'
    url:
      base: 'https://github.com/NatronGitHub/Natron/releases/'
      tag: 'tag/v'
      download: 'download/v'

# Downloads
downloads:
  items:
    windows:
      title: 'Windows'
      description: 'Supports Windows 8.1/10/11 x64.'
      icon: 'bxl-windows'
      versions:
        installer:
          title: 'Installer & Portable'
          url: ''
          suffix: '-Windows-x86_64.zip'
    linux:
      title: 'GNU/Linux'
      description: 'Supports any x86_64 distribution with X11, glibc 2.17+ and libgcc 4.8+.'
      icon: 'bxl-tux'
      versions:
        installer:
          title: 'Installer'
          url: ''
          suffix: '-Linux-x86_64.tgz'
        portable:
          title: 'Portable'
          url: ''
          suffix: '-Linux-x86_64-no-installer.tar.xz'
        flatpak:
          title: 'Flatpak'
          url: 'https://flathub.org/apps/details/fr.natron.Natron'
          suffix: ''
    macos:
      title: 'macOS'
      description: 'Supports from Snow Leopard up to the latest version of macOS running on Intel hardware.'
      icon: 'bxl-apple'
      versions:
        v11:
          title: 'Big Sur and later'
          url: ''
          suffix: '-macOS11-x86_64.dmg'
        v1015:
          title: 'Catalina'
          url: ''
          suffix: '-macOS1015-x86_64.dmg'
        v109:
          title: 'Mavericks, Yosemite, El Capitan, (High) Sierra, Mojave'
          url: ''
          suffix: '-OSX109-x86_64.dmg'
        v106:
          title: 'Snow Leopard, (Mountain) Lion'
          url: ''
          suffix: '-OSX-Universal.dmg'

# General
title: 'Natron'
description: 'Open Source Compositing Software For VFX and Motion Graphics'

# Home
home:
  hero:
    image: 'img/natron-baymax-screenshot.png'
    title: 'Visual Effects Without Limits.'
    description: 'Node-based compositing, backed by the freedom of open-source.'
    button:
      title: 'Download Natron'
      url: '#download'
  features:
    title: 'The tools you ºd expect to be here'
    description: 'The standard 2D compositing toolkit you already know and love.'
    items:
      openfx:
        image: 'img/index-feature-cards/openfx.svg'
        title: 'OpenFX Plugin Support'
        description: 'Natron supports industry-standard OFX plug-ins.'
      tracking:
        image: 'img/index-feature-cards/tracking.svg'
        title: '2D Tracking'
        description: 'Natron includes a fast, pixel-perfect 2D tracker.'
      roto:
        image: 'img/index-feature-cards/roto.svg'
        title: 'Roto'
        description: 'Multi-layered rotoscoping with per-vertex feathering.'
      keyer:
        image: 'img/index-feature-cards/keyer.svg'
        title: 'Keying'
        description: 'Natron offers various keying and matte refinement tools.'
      dopesheet:
        image: 'img/index-feature-cards/dopesheet.svg'
        title: 'Curve & Dope-sheet Editors'
        description: "If you've used a curve editor before you know how to use this one too."
      rendering:
        image: 'img/index-feature-cards/gpu.svg'
        title: 'GPU & Network Rendering'
        description: 'Natron is GPU accelerated and can be integrated with render farm managers.'

# Guide
guide:
  intro: 'guide/intro.html'
  getting_started: 'guide/getstarted.html'
  compositing: 'guide/compositing.html'
  tutorials: 'guide/tutorials.html'
  reference: '_group.html'
  developer: 'devel/index.html'

# External
# twitter: https://twitter.com/natronvfx (unmaintained)
discord: 'https://discord.gg/cpMj5p3Fv5'
forum: 'https://discuss.pixls.us/c/software/natron'
github: 'https://github.com/NatronGitHub/Natron'
facebook: 'https://facebook.com/groups/NatronNation'
docs: 'https://natron.readthedocs.io'
demos: 'https://sourceforge.net/projects/natron/files/Examples'

# Build settings
sass:
  style: compressed
markdown: kramdown
kramdown:
  auto_ids: "true"
  input: GFM
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
collections_dir: _collections
collections:
  features:
    output: true
    permalink: /features/:path/
plugins:
  - jekyll-feed
  - jekyll-redirect-from
